class Config:
    def __init__(self,
                 seed=None,
                 state_size=None,
                 action_size=None,
                 model_fn=None,
                 model_wrapper=None,
                 preprocessor=None,
                 buffer_size=None,
                 batch_size=None,
                 update_every=None,
                 max_steps=None,
                 gamma=None,
                 eps_start=None,
                 eps_end=None,
                 eps_decay=None,
                 tau=None):
        self.seed = seed
        self.state_size = state_size
        self.action_size = action_size
        self.build_model = model_fn
        self.model_wrapper = model_wrapper
        self.preprocessor = preprocessor
        self.buffer_size = buffer_size
        self.batch_size = batch_size
        self.update_every = update_every
        self.max_steps = max_steps
        self.gamma = gamma
        self.eps_start = eps_start
        self.eps_end = eps_end
        self.eps_decay = eps_decay
        self.tau = tau
